project:
  name: quickstart-tmax-tibero
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  template: templates/tmax-entrypoint.template.yaml

tests:
  deploy-tibero-1region-3az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      QSS3BucketName: $[taskcat_autobucket]
      RemoteAccessCIDR: 10.0.0.0/16
      DatabaseUserID: $[taskcat_genpass_6A]
      DatabaseUserPassword: P#$[taskcat_genpass_12A]
      KeyPairName: override
    regions:
      - us-west-2
