project:
  name: quickstart-tmax-tibero
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  template: templates/tmax_qs_tsc_obs_lamb_master.yaml

tests:
  deploy-tibero-1region-3az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      QSS3BucketName: $[taskcat_autobucket]
      RemoteAccessCIDR: --overrides--
      DatabaseUserID: --overrides--
      DatabaseUserPassword: --overrides--
      KeyPairName: --overrides--
    regions:
      - us-west-2