There is no cost to use this Quick Start, but you will be billed for any AWS services or resources that this Quick Start deploys. For more information, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^].

== Software licenses

This deployment uses a Bring Your Own License (BYOL) model for {partner-product-short-name} Database Cloud Edition. To download the software, you must already own licenses for {partner-product-short-name} Database Cloud Edition, and you must have access to {partner-company-name} https://technet.tmaxsoft.com/en/front/main/main.do[TechNet^].

This Quick Start launches the Amazon Machine Image (AMI) for the Red Hat Enterprise Linux (RHEL) operating system. For details, refer to https://aws.amazon.com/partners/redhat/rhel-pricing/[Red Hat Enterprise Linux on AWS Pricing^].

You can find following Tibero offerings in AWS Marketplace:

*   https://aws.amazon.com/marketplace/pp/prodview-bpnsx6y2wqyhq?sr=0-1&ref_=beagle&applicationId=AWSMPContessa[Tibero TAC (Tibero Active Cluster)^], which offers reliable, seamless service even in failure situations.
*   https://aws.amazon.com/marketplace/pp/prodview-oqp2jrkq622mg?sr=0-4&ref_=beagle&applicationId=AWSMPContessa[Tibero 6 Enterprise Edition (CloudFormation)^]. Tibero 6 is a high-performance, highly secure, highly scalable relational database management system (RDBMS).
*   https://aws.amazon.com/marketplace/pp/prodview-sxyqek4rcmbzm?sr=0-2&ref_=beagle&applicationId=AWSMPContessa[Tibero 6 Standard Edition^], which offers a free trial.
*   https://aws.amazon.com/marketplace/pp/prodview-qck3d4udqa2zm?sr=0-3&ref_=beagle&applicationId=AWSMPContessa[Tibero 6 Enterprise Edition^], which offers a free trial.